### ISSUE TITLE
Can't take input!

### ISSUE THREAD

**Issue by nirmalnishant645** [nirmalnishant645/HackeRank#2]

**Comment by anantkaushik** [comment]
Try to use input() instead of raw_input()

**Comment by nirmalnishant645** [comment]
in

**Comment by nirmalnishant645** [comment]
n = int(raw_input())

elements = raw_input().strip().split()

l = []
for i in range(0, n):
    l.append(int(elements[i]))

t = tuple(l)

print (hash(t))

**Comment by anantkaushik** [comment]
`
n = int(input())

elements = input().strip().split()

l = []
for i in range(0, n):
l.append(int(elements[i]))

t = tuple(l)

print (hash(t))
`
