### ISSUE TITLE
C++ code for Generics is not working

### ISSUE THREAD

**Issue by anantkaushik** [nirmalnishant645/HackeRank#3]
Your code for 'Generics' exercise is giving errors while submitting.

**Comment by nirmalnishant645** [comment]
//Try This
#include <iostream>
#include <vector>
#include <string>
using namespace std;
template <typename T> void printArray(vector<T> a) {
  for (T i : a)
    cout << i << endl;
}
int main() {
	int n;
	
	cin >> n;
	vector<int> int_vector(n);
	for (int i = 0; i < n; i++) {
		int value;
		cin >> value;
		int_vector[i] = value;
	}
	
	cin >> n;
	vector<string> string_vector(n);
	for (int i = 0; i < n; i++) {
		string value;
		cin >> value;
		string_vector[i] = value;
	}
	printArray<int>(int_vector);
	printArray<string>(string_vector);
	return 0;
}
